version: "3"

services:
  charity:
    image: charity:latest
    ports:
      - 8081:8081
    depends_on:
      - db1
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db1:3306/charity_donation?serverTimezone=UTC&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - 9092:9092
    environment:
      - ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_PORT=9092
    depends_on:
      - zookeeper

  db1:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --skip-character-set-client-handshake
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=charity_donation
    volumes:
      - /home/charity/db:/var/lib/mysql

  adminer:
   image: adminer
   ports:
      - "5000:8080"


