version: "3"

networks:
  kafka-net:
    driver: bridge

services:
  charity:
    image: charity:latest
    ports:
      - "8081:8081"
    depends_on:
      - db1
      - kafka-server1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db1:3306/charity_donation?serverTimezone=UTC&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root

  zookeeper-server:
    image: 'bitnami/zookeeper:3.4.10'
    networks:
      - kafka-net
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server1:
    image: 'bitnami/kafka:0.11.0-1-r1'
    networks:
      - kafka-net    
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server

  db1:
    image: mysql:5.7
    container_name: db1
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=charity_donation
    volumes:
      - /home/Pulpit/CodersLab/charity/db:/var/lib/mysql

  adminer:
   image: adminer
   ports:
      - "5000:8080"


